name: Multi-Job demo

on:
  push:
    branches: [ main ]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout my code
        uses: actions/Checkout@v4

      - name: list all files
        run: ls -la

      - name: check index.html exists
        run: echo "Files look good!"
      
  notify-done:

    runs-on: ubuntu-latest

    needs: check-files

    steps:
      - name: Success message
        run: echo "check-files passed!"